/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RestService } from "./core/services/rest.service";
import { GoToDetailPageEvent, Page } from "./core";
export namespace Components {
    interface CrudComponent {
        "baseUrl": string;
        "listDisplay": string;
        "resourcePath": string;
    }
    interface CrudDetail {
        "objectId": string;
        "restService": RestService;
    }
    interface CrudList {
        "restService": RestService;
    }
}
declare global {
    interface HTMLCrudComponentElement extends Components.CrudComponent, HTMLStencilElement {
    }
    var HTMLCrudComponentElement: {
        prototype: HTMLCrudComponentElement;
        new (): HTMLCrudComponentElement;
    };
    interface HTMLCrudDetailElement extends Components.CrudDetail, HTMLStencilElement {
    }
    var HTMLCrudDetailElement: {
        prototype: HTMLCrudDetailElement;
        new (): HTMLCrudDetailElement;
    };
    interface HTMLCrudListElement extends Components.CrudList, HTMLStencilElement {
    }
    var HTMLCrudListElement: {
        prototype: HTMLCrudListElement;
        new (): HTMLCrudListElement;
    };
    interface HTMLElementTagNameMap {
        "crud-component": HTMLCrudComponentElement;
        "crud-detail": HTMLCrudDetailElement;
        "crud-list": HTMLCrudListElement;
    }
}
declare namespace LocalJSX {
    interface CrudComponent {
        "baseUrl"?: string;
        "listDisplay"?: string;
        "resourcePath"?: string;
    }
    interface CrudDetail {
        "objectId"?: string;
        "onPageChange"?: (event: CustomEvent<Page>) => void;
        "restService"?: RestService;
    }
    interface CrudList {
        "onGoToDetail"?: (event: CustomEvent<GoToDetailPageEvent>) => void;
        "onPageChange"?: (event: CustomEvent<Page>) => void;
        "restService"?: RestService;
    }
    interface IntrinsicElements {
        "crud-component": CrudComponent;
        "crud-detail": CrudDetail;
        "crud-list": CrudList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "crud-component": LocalJSX.CrudComponent & JSXBase.HTMLAttributes<HTMLCrudComponentElement>;
            "crud-detail": LocalJSX.CrudDetail & JSXBase.HTMLAttributes<HTMLCrudDetailElement>;
            "crud-list": LocalJSX.CrudList & JSXBase.HTMLAttributes<HTMLCrudListElement>;
        }
    }
}
